name: Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TIME: false
          
      - name: generate-snake
        uses: Platane/snk/svg-only@v2
        with: 
              github_user_name: ${{ github.repository_owner }}
              outputs: |
                  ./snakes/dark.svg?palette=github-dark&&color_snake=blue
                  ./snakes/light.svg?color_snake=#7845ab
                  ./snakes/ocean.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: commit-and-push
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
              commit_message: Upgrade Snake
